/// Linear GraphQL schema module generated by cynic.
///
/// This is expensive to compile (~4 min) and should rarely change.
/// Isolating it in its own crate prevents recompilation when
/// editing handler/CLI code in the main crate.
#[cynic::schema("linear")]
pub mod schema {}

// ── Scalar types ──

/// DateTime scalar — wraps a String ISO-8601 timestamp
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct DateTime(pub String);

impl cynic::schema::IsScalar<schema::DateTime> for DateTime {
    type SchemaType = schema::DateTime;
}

/// TimelessDate scalar — wraps a String date (no time component)
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct TimelessDate(pub String);

impl cynic::schema::IsScalar<schema::TimelessDate> for TimelessDate {
    type SchemaType = schema::TimelessDate;
}
